#!/bin/sh

./configure --with-sound=no \
	    --with-x-toolkit=lucid \
	    --with-cairo \
	    --with-xft \
	    --with-harfbuzz \
	    --with-libotf \
	    --with-m17n-flt \
	    --without-lcms2 \
	    --without-xml2 \
	    --without-toolkit-scroll-bars \
	    --with-gnutls=ifavailable \
	    --with-ns=no \
	    --with-xwidgets=no \
	    --without-compress-install

