[memory_usage]
disabled = false

[vagrant]
disabled = true

[vcsh]
disabled = true

[hg_branch]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[purescript]
disabled = true

[red]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[nim]
disabled = true

[aws]
disabled = true

[battery]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[helm]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true