#!/bin/sh

# Configure gcc to build libgccjit with musl libc

../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info \
	     --libexecdir=/usr/lib --libdir=/usr/lib --enable-threads=posix \
	     --enable-__cxa_atexit --disable-multilib --with-system-zlib \
	     --enable-shared --enable-lto --enable-plugins --enable-linker-build-id \
	     --disable-werror --disable-nls --enable-default-pie  --enable-default-ssp \
	     --enable-checking=release --disable-libstdcxx-pch --with-isl \
	     --disable-libunwind-exceptions --disable-target-libiberty --disable-libvtv \
	     --enable-fast-character --enable-vtable-verify --build=x86_64-linux-musl \
	     --disable-libsanitizer --disable-symvers libat_cv_have_ifunc=no \
	     --enable-host-shared --enable-languages=c,c++,jit,lto

